### ISSUE TITLE
asa custom containers for frontend (node.js) and python microservices (az-openai) are failing to start

### ISSUE THREAD

**Issue by thegovind** [Azure/reddog-solutions#34] opened 2023-04-07 05:24 UTC
- Custom containers on port `1025` are not starting for frontend and python services when deployed to ASA standard

**Comment by moarychan** [comment] 2023-04-17 03:10
It just deployed successfully, and the frontend page can show the data responded from backend,
![image](https://user-images.githubusercontent.com/19926623/232368597-ab785d8b-17c2-4370-8260-2104d1c8266c.png)

**Comment by LGDoor** [comment] 2023-04-17 05:59
Can't reproduce this issue. The deployment was successful on my side.

**Comment by saragluna** [comment] 2023-04-24 04:40
Closing this issue now for cannot reproduce it.

**Closed by saragluna** 2023-04-24 04:40 UTC
Labels: bug
